### ISSUE TITLE
实体字段上注解没啥用，还是返回明文

### ISSUE THREAD

**Issue by tianxiajiangshan** [lzhpo/sensitive-spring-boot-starter#1]
实体字段上注解没啥用，还是返回明文

**Comment by lzhpo** [comment]
您好，有用的！
![image](https://user-images.githubusercontent.com/42663571/180499855-094cd63f-b1f7-4324-8460-eae6c7eaea1c.png)

请按照文档使用，检查你是否在Controller类或当前接口的方法上使用了`@IgnoreSensitive`注解，此注解是用于忽略脱敏的。

可以参考测试用例中的代码：
1. [sample1-entity](https://github.com/lzhpo/sensitive-spring-boot-starter/blob/master/src/test/java/com/lzhpo/sensitive/entity/SensitiveEntity.java)
2. [sample1-API](https://github.com/lzhpo/sensitive-spring-boot-starter/blob/master/src/test/java/com/lzhpo/sensitive/controller/SensitiveController.java)

如果你还有其它问题，你可以随时打开此issue，最好提供一份仓库示例，我去帮你check一下，谢谢！

**Comment by tianxiajiangshan** [comment]
就是pom引入依赖，实体类字段加注解，controller没做改动没加忽略注解返回对象List<entity>，都是明文

**Comment by tianxiajiangshan** [comment]
<dependency>
				<groupId>com.lzhpo</groupId>
				<artifactId>sensitive-spring-boot-starter</artifactId>
				<version>${sensitive.version}</version>
			</dependency>
controller中
List<User> list = userService.selectUserList(user);

entity
/** 用户名称（姓名或昵称） */
    @Excel(name = "用户名称", readConverterExp = "姓名或昵称")
    @Sensitive(strategy = SensitiveStrategy.CHINESE_NAME, replacer = '*')
    private String userName;
    /** 手机号码 */
    @Excel(name = "手机号码")
    @Sensitive(strategy = SensitiveStrategy.MOBILE_PHONE, replacer = '*')
    private String phoneNumber;

    /** 身份证号码 */
    @Excel(name = "身份证号码")
    @Sensitive(strategy = SensitiveStrategy.ID_CARD, replacer = '*')
    private String idcardNumber;

**Comment by w1023563646** [comment]
我遇到的问题是一样的，就最简单的引入依赖，实体类加注解 不掩码
