### ISSUE TITLE
都是明文的

### ISSUE THREAD

**Issue by tianxiajiangshan** [lzhpo/sensitive-spring-boot-starter#2]
就是pom引入依赖，实体类字段加注解，controller没做改动没加忽略注解返回对象List，都是明文

		<dependency>
			<groupId>com.lzhpo</groupId>
			<artifactId>sensitive-spring-boot-starter</artifactId>
			<version>1.0.8</version>
		</dependency>

controller中
List list = userService.selectUserList(user);

entity中
/** 用户名称（姓名或昵称） /
@Excel(name = "用户名称", readConverterExp = "姓名或昵称")
@sensitive(strategy = SensitiveStrategy.CHINESE_NAME, replacer = '')
private String userName;

/** 手机号码 /
@Excel(name = "手机号码")
@sensitive(strategy = SensitiveStrategy.MOBILE_PHONE, replacer = '')
private String phoneNumber;

/** 身份证号码 */
@Excel(name = "身份证号码")
@Sensitive(strategy = SensitiveStrategy.ID_CARD, replacer = '*')
private String idcardNumber;

**Comment by tianxiajiangshan** [comment]
你这是entity的还行吧，@bulider的Mockhelper，list获取mybatis返回的集合的怎么处理

**Comment by lzhpo** [comment]
谢谢你提出的问题，现已支持多层嵌套属性脱敏，使用方式不变，并已发布至Maven中央仓库，请耐心等待Maven中央仓库同步，maybe今天晚上或者明天！

说明文档：[有关单独使用@Builder注解、实体类多层嵌套问题](https://github.com/lzhpo/sensitive-spring-boot-starter#1%E6%9C%89%E5%85%B3%E5%8D%95%E7%8B%AC%E4%BD%BF%E7%94%A8builder%E6%B3%A8%E8%A7%A3%E5%AE%9E%E4%BD%93%E7%B1%BB%E5%A4%9A%E5%B1%82%E5%B5%8C%E5%A5%97%E9%97%AE%E9%A2%98)

Release detail: [https://github.com/lzhpo/sensitive-spring-boot-starter/releases/tag/1.0.9](https://github.com/lzhpo/sensitive-spring-boot-starter/releases/tag/1.0.9)
