### ISSUE TITLE
'@Sensitive' not applicable to local variable

### ISSUE THREAD

**Issue by wangkailun** [lzhpo/sensitive-spring-boot-starter#3]
`        @Sensitive(strategy = SensitiveStrategy.BANK_CARD , replacer = '*')
                private String CARD;
`
我在GetMapping function中这样使用提示 '@Sensitive' not applicable to local variable 请问使用的时候是有什么限制规则吗？

**Comment by lzhpo** [comment]
你好，用在类的字段中即可，不是方法里面，可以参考我写的测试用例：[SensitiveEntity](https://github.com/lzhpo/sensitive-spring-boot-starter/blob/master/src/test/java/com/lzhpo/sensitive/test/entity/SensitiveEntity.java)
